# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
plugins:
#  - jekyll-feed
#  - jekyll-redirect-from
  - jekyll-seo-tag
#  - jekyll-sitemap
#  - jekyll-avatar
#  - jemoji
#  - jekyll-mentions
#  - jekyll-include-cache

lang: en-CA
title: Devvyn.io
sub_title: Software Engineer | Designer | Problem Solver
author: Devvyn PM
description: >
  This site is about Devvyn Patrick Murphy, a software developer in Saskatoon,
  Saskatchewan, Canada. Learn about Devvyn's personality and where to find this
  human's online material.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://devvyn.io" # the base hostname & protocol for your site, e.g. http://example.com
email: devvyn@devvyn.io
twitter_username: devvyn
github_username:  devvyn
youtube_username: devvynmurphy
facebook_username: devvyn

# immutable
lsi: false
#safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
#source: <repo>

# mutable defaults
encoding: UTF-8
future: true
jailed: false
theme: minima
gfm_quirks: paragraph_end

# other
collections:
  articles:
    output: true
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - README.md
kramdown:
  math_engine: mathjax
  input: GFM
  hard_wrap: false
# immutable
  math_engine: mathjax
  syntax_highlighter: rouge

# user specified defaults

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post

