version: "3"
services:
  jekyll:
    image: jekyll/builder:pages
    command: jekyll serve
    container_name: jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    networks:
      - webnet
networks:
  webnet:
