version: "3"
services:
  jekyll:
    image: jekyll/builder:pages
    command: jekyll serve
    container_name: jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - "80:4000"
    networks:
      - webnet
    deploy:
      resources:
        limits:
          memory: 500M
      restart_policy:
        condition: never
networks:
  webnet: